#pragma once

#include "stm32g4xx_hal.h"
#include <stdint.h>

/* Use the I2C handle generated by CubeMX */
extern I2C_HandleTypeDef hi2c2;

/* Try 0x5D first (most common). If no ACK, try 0x14 */
#define GT911_I2C_ADDR_7BIT   (0x5D)
#define GT911_I2C_ADDR        (GT911_I2C_ADDR_7BIT << 1)

/* IO functions required by GT911 driver */
int32_t GT911_IO_Init(void);
int32_t GT911_IO_DeInit(void);
int32_t GT911_IO_ReadReg(uint16_t devAddr, uint16_t reg, uint8_t *pData, uint16_t len);
int32_t GT911_IO_WriteReg(uint16_t devAddr, uint16_t reg, uint8_t *pData, uint16_t len);
int32_t GT911_IO_GetTick(void);
